---
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Creating Roles directory
    file: path=/home/test/playbooks/roles state=directory
  - name: Creating Roles child directory
    file: path=/home/test/playbooks/roles/{{ item }} state=directory
    with_items:
    - appservers
    - cachingservers
    - common
    - webservers
  - name: Creating AppServer Roles child directory
    file: path=/home/test/playbooks/roles/appservers/{{ item }} state=directory
    with_items:
    - defaults
    - files
    - handlers
    - meta
    - tasks
    - templates
    - vars
  - name: Creating Caching Servers Roles child directory
    file: path=/home/test/playbooks/roles/cachingservers/{{ item }} state=directory
    with_items:
    - defaults  
    - files         
    - handlers
    - meta      
    - tasks
    - templates
    - vars
  - name: Creating Web Servers Roles child directory
    file: path=/home/test/playbooks/roles/webservers/{{ item }} state=directory
    with_items:
    - defaults
    - files
    - handlers
    - meta
    - tasks
    - templates
    - vars
  - name: Creating Common Roles child directory
    file: path=/home/test/playbooks/roles/common/{{ item }} state=directory
    with_items:
    - defaults
    - files
    - handlers
    - meta
    - tasks
    - templates
    - vars
