--- # Testing the J2 Template Module
- hosts: apacheweb:aptserver
  connection: ssh
  user: test
  sudo: yes
  gather_facts: yes
  vars:
    userName: test
    userPassword: password123
    connectionType: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      template: src=/home/test/playbooks/files/test.conf.j2 dest=/home/test/test.conf owner=test group=test mode=750 
